name: Docs

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          # remind: Antora runs faster on Node 10
          node-version: '10'
      - run: npm ci
      - run: npm run build
      - run: npm run lint
